# CHANGE LOG
# - 2026-03-09 | Request: Tag-only mode | Point generated lists to the library folder.
# - 2026-01-05 | Request: Generated lists | Create 90s, creative, and underrepresented lists.

import os
from datetime import datetime

root = os.path.join(os.environ.get("LOCALAPPDATA", ""), "PromptLoom", "Library", "Generated")
if not os.path.isdir(root):
    raise SystemExit(f"Generated folder not found: {root}")

date = datetime.now().strftime("%Y-%m-%d")
header = f"# CHANGE LOG\n# - {date} | Request: Generated lists | Initial content.\n"

data = {
    os.path.join("Person", "90s-women.txt"): [
        "90s supermodel",
        "runway supermodel",
        "catalog model",
        "editorial model",
        "music video model",
        "denim model",
        "grunge model",
        "rave model",
        "club kid",
        "dance model",
        "street model",
        "urban model",
        "lookbook model",
        "fashion model",
        "glamour model",
        "swimwear model",
        "lingerie model",
        "pinup model",
        "beauty model",
        "studio model",
        "portrait model",
        "cover model",
        "vogue model",
        "runway talent",
        "campaign model",
        "print model",
        "commercial model",
        "fitness model",
        "aerobics model",
        "roller skater",
        "skate model",
        "club dancer",
        "rave dancer",
        "stage dancer",
        "nightlife model",
        "party model",
        "festival model",
        "beach model",
        "poolside model",
        "arcade regular",
        "mall regular",
        "record store regular",
        "video store regular",
        "radio host",
        "tv host",
        "pop singer",
        "rock singer",
        "hip hop dancer",
        "breakdancer",
        "dj performer",
        "club performer",
    ],
    os.path.join("Person", "creative-features.txt"): [
        "mirror twin",
        "hologram muse",
        "glass skin",
        "chrome freckles",
        "circuit lashes",
        "neon lashes",
        "prism eyes",
        "halo eyes",
        "iris rings",
        "glow pupils",
        "fog eyes",
        "smoke eyes",
        "shadow freckles",
        "ink freckles",
        "constellation freckles",
        "galaxy eyeliner",
        "circuit eyeliner",
        "wire eyeliner",
        "lace eyeliner",
        "smoke lips",
        "glass lips",
        "mirror lips",
        "hologram lips",
        "gloss ripple",
        "metallic blush",
        "paper skin",
        "porcelain mask",
        "velvet skin",
        "crystal skin",
        "granite skin",
        "marble skin",
        "inked veins",
        "gold leaf skin",
        "silver leaf skin",
        "glass tear tracks",
        "chrome tears",
        "hologram tears",
        "light streak hair",
        "fiber hair",
        "tinsel hair",
        "rainbow strands",
        "braid lattice",
        "hair ribbons",
        "hair rings",
        "mask jewelry",
        "face chains",
        "cheek studs",
        "brow studs",
        "lip studs",
        "temple gems",
        "jaw gems",
        "collar gems",
    ],
    os.path.join("Person", "underrepresented-features.txt"): [
        "freckles",
        "birthmarks",
        "beauty marks",
        "vitiligo",
        "albinism",
        "scar",
        "stretch marks",
        "cellulite",
        "tan lines",
        "body hair",
        "arm hair",
        "armpit hair",
        "pubic hair",
        "short hair",
        "buzz cut",
        "pixie cut",
        "curly hair",
        "coily hair",
        "natural hair",
        "braids",
        "box braids",
        "cornrows",
        "locs",
        "tight curls",
        "thin brows",
        "thick brows",
        "gap teeth",
        "crooked teeth",
        "diastema",
        "small bust",
        "flat chest",
        "narrow hips",
        "broad shoulders",
        "strong jaw",
        "square jaw",
        "round face",
        "long face",
        "wide nose",
        "button nose",
        "upturned nose",
        "downturned nose",
        "thick lips",
        "thin lips",
        "small lips",
        "wide lips",
        "soft chin",
        "pointed chin",
        "asymmetry",
        "moles",
        "skin texture",
    ],
    os.path.join("Setting", "90s-settings.txt"): [
        "arcade",
        "video store",
        "record store",
        "music store",
        "cassette shop",
        "cd shop",
        "mall food court",
        "shopping mall",
        "roller rink",
        "skate park",
        "bowling alley",
        "diner",
        "pizza parlor",
        "burger joint",
        "drive-in theater",
        "movie theater",
        "multiplex",
        "comic shop",
        "game shop",
        "internet cafe",
        "computer lab",
        "photo studio",
        "tv studio",
        "radio studio",
        "music studio",
        "dance studio",
        "aerobics studio",
        "gym",
        "pool",
        "poolside",
        "locker room",
        "laundromat",
        "car wash",
        "gas station",
        "convenience store",
        "corner store",
        "newsstand",
        "bookstore",
        "coffee shop",
        "subway platform",
        "bus stop",
        "parking lot",
        "parking garage",
        "street corner",
        "alleyway",
        "rooftop",
        "apartment",
        "loft",
        "bedroom",
        "living room",
        "kitchen",
    ],
    os.path.join("Setting", "creative-settings.txt"): [
        "mirror maze",
        "glass tunnel",
        "hologram hallway",
        "light grid room",
        "neon greenhouse",
        "floating library",
        "orbital lounge",
        "sky bridge",
        "water gallery",
        "underwater lounge",
        "rain room",
        "fog room",
        "sound chamber",
        "echo hall",
        "wind tunnel",
        "gravity room",
        "infinity room",
        "reflection pool",
        "glow stage",
        "shadow stage",
        "paper house",
        "fabric hall",
        "origami studio",
        "mirror studio",
        "prism studio",
        "glass studio",
        "ice studio",
        "stone studio",
        "metal studio",
        "laser room",
        "light tunnel",
        "ribbon room",
        "string room",
        "thread room",
        "film set",
        "sound stage",
        "light stage",
        "dream chamber",
        "memory room",
        "time room",
        "signal room",
        "satellite room",
        "cloud room",
        "sky room",
        "sea room",
        "sand room",
        "forest room",
        "garden room",
        "tide room",
        "lunar room",
        "solar room",
    ],
    os.path.join("Setting", "underrepresented-settings.txt"): [
        "laundromat",
        "storage unit",
        "back office",
        "service corridor",
        "utility room",
        "maintenance room",
        "freight elevator",
        "stairwell",
        "loading dock",
        "warehouse aisle",
        "warehouse office",
        "shipping bay",
        "packing room",
        "mail room",
        "copy room",
        "break room",
        "server room",
        "electrical room",
        "janitor closet",
        "supply closet",
        "garage bay",
        "parking garage",
        "parking deck",
        "bus depot",
        "train platform",
        "subway tunnel",
        "service alley",
        "back alley",
        "roof access",
        "mechanical roof",
        "fire escape",
        "bike storage",
        "loading ramp",
        "side entrance",
        "rear entrance",
        "basement hall",
        "basement room",
        "attic room",
        "workshop",
        "tool room",
        "craft room",
        "stock room",
        "supply room",
        "machine room",
        "boiler room",
        "pump room",
        "air shaft",
        "vent room",
        "trash room",
        "recycling room",
    ],
}

for rel_path, entries in data.items():
    if len(entries) != len(set(entries)):
        raise SystemExit(f"{rel_path} has duplicate entries")

for rel_path, entries in data.items():
    abs_path = os.path.join(root, rel_path)
    os.makedirs(os.path.dirname(abs_path), exist_ok=True)
    content = header + "\n" + "\n".join(entries) + "\n"
    with open(abs_path, "w", encoding="utf-8") as f:
        f.write(content)

print(f"Wrote {len(data)} files under {root}")
